alias clang='docker run -it -u $(id -u):$(id -g) --rm -v ${PWD}:/work -w /work silkeh/clang clang'
alias d='cd ~/desktop'
alias docui='docker run --rm -itv /var/run/docker.sock:/var/run/docker.sock skanehira/docui'
alias gdb='gdb -q'
alias ls='ls -hF --color=auto'
alias mv='mv -i -v'
alias sl='ls'
alias vim='nvim'
alias aws='docker run --rm -ti -v ~/.aws:/root/.aws -v $(pwd):/aws --net=host amazon/aws-cli'
alias psql="docker run --rm -it --net=host postgres:12 psql"
alias dc='docker compose'
alias backlight='sudo tee /sys/class/backlight/intel_backlight/brightness'
alias wget='wget -c --content-disposition'
alias cg='cd $(git rev-parse --show-toplevel)'
alias latexc='docker run --rm -u $(id -u):$(id -g) -v $(pwd):/workdir latex-env:0.0.1 latexmk'
alias wget='wget --content-disposition'
alias send='cp -v $(ls -a | fzf -0 -1) /mnt/nas/Cache'
alias sage='docker run -it -v $(pwd):/sage-scripts ghcr.io/laika/sagemath:latest sage'
alias ghidra='docker run -itd -e=DISPLAY=${DISPLAY:-100.96.159.88:0.0} --net=host --name=ghidra --rm -v ${HOME}/.ghidra:/home/ghidra/.ghidra -v $(pwd):/share ghcr.io/laika/ghidra:latest >/dev/null'
alias gdb='docker run -it --rm --cap-add=SYS_PTRACE --security-opt="seccomp=unconfined" --net=host -v $(pwd):/share ghcr.io/laika/gdb:latest gdb'
alias poe='poetry poe'
alias bfg='java -jar /opt/bfg-1.14.0.jar'
alias erp='interpreter --fast'
# alias q='docker run --rm -it ghcr.io/natesales/q'
[[ $(command -v rsync) ]] && alias cp='rsync -ah --info=progress2'
[[ -f ${HOME}/.scripts/fzf-clipboard ]] && alias paste='${HOME}/.scripts/fzf-clipboard'
[[ $(command -v bibtex-tidy) ]] && alias bibtex-format='bibtex-tidy --curly --blank-lines --duplicates --trailing-commas'
[[ $(command -v z) ]] && alias cd='z'
[[ $(command -v eza) ]] && alias ls='eza -F --group-directories-first' || alias ls='ls -hF --color=auto'
[[ $(command -v eza) ]] && alias tree='eza -T -L 3 -a -I "node_modules|.git|.cache" --icons'
[[ $(command -v fdfind) ]] && alias fd='fdfind'
[[ $(command -v procs) ]] && alias ps='procs'
[[ $(command -v rg) ]] && alias rg='rg --max-columns-preview'
[[ $(command -v trash-put) ]] && alias rm='trash-put'
[[ $(command -v tty-clock) ]] && alias clock='tty-clock -s -c'
[[ $(command -v xclip) ]] && alias copy='xclip -selection c'
[[ $(command -v wl-copy) ]] && alias copy='wl-copy'
[[ $(command -v kitty) ]] && alias icat='kitty +kitten icat'
[[ $(command -v pwninit) ]] && alias pwninit='pwninit --no-template'
[[ $(command -v minikube) ]] && alias k='minikube kubectl --'
[[ $(command -v kubectl) ]] && alias k='kubectl --'
[[ $(command -v makers) ]] && alias m='makers'

# Git
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias gc='git commit -m'
alias gp='git push'


alias uhd_usrp_probe='docker run --rm -ti --privileged --device /dev/bus/usb/:/dev/bus/usb/ -v /usr/share/uhd/images:/usr/share/uhd/images openverso/ettus-uhd:3.15.0 uhd_usrp_probe'
alias uhd_find_devices='docker run --rm -ti --privileged   --device /dev/bus/usb/:/dev/bus/usb/   -v /usr/share/uhd/images:/usr/share/uhd/images   openverso/ettus-uhd:3.15.0 uhd_find_devices'

alias c++='docker run --rm -v "${PWD}:/usr/src/myapp" -v "${HOME}/comp/ac-library:/opt/ac-library" -w /usr/src/myapp gcc:12 g++ -std=gnu++2b -O2 -DONLINE_JUDGE -DATCODER -Wall -Wextra -mtune=native -march=native -fconstexpr-depth=2147483647 -fconstexpr-loop-limit=2147483647 -fconstexpr-ops-limit=2147483647 -I/opt/ac-library'
